homeassistant:
  whitelist_external_dirs:
    - /config/
  customize: !include customize.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Enables the frontend
frontend:
  themes: !include themes.yaml
# Health
system_health:
# Enables configuration UI
config:
# Track the sun
sun:
# ffmpeg
ffmpeg:
# stream
stream:
# Cloud
cloud:
# Mobile app
mobile_app:
##
automation: !include automations.yaml
script: !include scripts.yaml
recorder: !include recorder.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
zone: !include zone.yaml
ios: !include ios_notify.yaml
camera: !include camera.yaml
light: !include light.yaml
group: !include group.yaml
climate: !include climate.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
input_number: !include input_number.yaml
google_assistant: !include google_assistant_project.yaml
logger: !include logger.yaml
homekit: !include homekit.yaml
browser_mod: !include browser_mod.yaml
input_select: !include input_select.yaml
notify: !include notify.yaml
vacuum: !include vacuum.yaml
samsungtv: !include samsung-tv.yaml


# wol
wake_on_lan:


# shell_command
shell_command:
 reboot_yicamera: curl http://192.168.1.125/cgi-bin/reboot.sh


# counter
counter:
  volume_stereo:
    step: 1
    minimum: 0
    maximum: 40


# SSL
http:
   base_url: !secret duckdns
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem
   #api_password: !secret http_password


# Google Calendar
google:
  client_id: !secret calendar_client_id
  client_secret: !secret calendar_client_secret


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'it'
    cache: false


# SMARTLIFE
tuya:
  username: !secret tuya_name 
  password: !secret tuya_psw 
  country_code: 39
  platform: smart_life


# EWELINK SONOFF
sonoff:
  username: !secret sonoff_name
  password: !secret sonoff_password
  scan_interval : 3 
  grace_period : 600
  api_region: 'eu'


# IFTTT
#ifttt:
# key: !secret iftt_key


# MQTT
mqtt:
  broker: core-mosquitto
  port: 1883
  username: !secret mqtt_admin
  password: !secret mqtt_psw


# Smartir
smartir:
  update_branch: rc


# Speed-test
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload


# Hacs
hacs:
  token: !secret hacs_token


# favicon https://github.com/thomasloven/hass-favicon
favicon:
  title: Casa
  icon_path: /local/favicon/


# HassKit
notify_hasskit:
  token:
    - !secret hasskit_token


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
##########
##########
#––––––––#